### DISCUSSION TITLE
Customise Bespoke's progress bar via theme's CSS

### DISCUSSION THREAD

**Discussion by mil-ad** [marp-team/marp#201] [Q&A] [answered]
Is it possible to customise bespoke's progress bar directly from my theme's CSS/SASS?

I tried adding something below to my sass but it doesn't seem to be picked up:

```css
.bespoke-progress-bar {
    background: red !important;
}
```

I can of course tweak it from Chrome's dev tools but when I copy/paste the rule directly into my CSS it's still not picked up:

```css
body[data-bespoke-view=""] .bespoke-progress-parent .bespoke-progress-bar {
    background: green !important;
}
```

**Comment by yhatt** [comment, marked as answer]
It cannot. Theme CSS cannot interfere with the outside of Marp slides to prevent breaking Marp-integrated tools. In addition, Marp CLI's bespoke template is not designed for customizable for now.

If you really want to change the color, a following hack is working:

```css
@import url('data:text/css,.bespoke-progress-bar { background: red !important; }');
```

CSS `@import` rule can bypass Marp(it)'s postprocess for scoping styles to the slide. _It's just a hack that is similar to marp-team/marp-cli#358_ so honestly we could never recommend.
