### DISCUSSION TITLE
Custom two column layout doesn't look right when exported

### DISCUSSION THREAD

**Discussion by mil-ad** [marp-team/marp#203] [Q&A] [answered]
I have this custom CSS/sass to do two columns layout which I found somewhere here in the github issues:

```css
div.twocols {
  margin-top: 35px;
  column-count: 2;
}

div.twocols p:first-child,
div.twocols h1:first-child,
div.twocols h2:first-child,
div.twocols ul:first-child,
div.twocols ul li:first-child,
div.twocols ul li p:first-child {
  margin-top: 0 !important;
}

div.twocols p.col_break {
  break-before: column;
  margin-top: 0;
}
```

which means I can a have a slide like below

```md
---
<div class="twocols">

First Columns

- one
- two
- three

<p class="col_break">

Second Column

- four
- five
- six

</div>
```

and get something like below

![image](https://user-images.githubusercontent.com/686449/139731007-5f15fbb7-56b1-4aaa-a936-8607182a69cf.png)

This looks fine in VS Code's preview pane or when I open the HTML file. However, when I try to export it to PDF (either through VS Code export command orby  printing as PDF in Chrome) the margins get funny and I get:

![image](https://user-images.githubusercontent.com/686449/139731173-f9fd31e7-a643-4416-b7db-f1a7585e41f1.png)

Does anyone have an idea what I'm doing wrong in that CSS?

**Comment by mil-ad** [comment]
It might actually be easier to do below to get multiple columns:

```css
div.columns_wrapper {
  display: flex;
}

.column {
  flex: 50%;
}
```
