### DISCUSSION TITLE
Split header-footer with logos

### DISCUSSION THREAD

**Discussion by devster31** [marp-team/marp#244] [Q&A] [answered]
Hello, I'm having some issues replicating the following template:
![image](https://user-images.githubusercontent.com/1912062/146973650-5c6987e3-981f-4d05-b8e1-54ed83aa0277.png)

In particular I'm having issues with the header (I can't make the image stick to the left -or right- side), and the footer (also an alignment problem), as well as CSS directives for color.

I'm using the following snippet to override the default theme:
```css
header: <div> <div> one </div> <div> <img src="https://www.unidformazione.com/wp-content/uploads/2017/10/UniBo-Universita-di-Bologna.png" /> </div> </div>
footer: Alma Mater - University of Bologna
style: |
    header {
        display: grid;
        grid-template-rows: 1fr;
        grid-template-columns: 1fr 1fr;
        grid-gap: 10px;
        box-sizing: border-box;
        justify-content: center;
        width: 100%;
    }

    header img {
        height: 100px;
    }

    footer {
        display: grid;
        grid-template-columns: 1fr max-content;
        background-color: #bb2e29;
        align-content: right;
    }
```
but the following is the result:
![image](https://user-images.githubusercontent.com/1912062/146974814-8974eeb4-9375-4065-9926-9c808fc30ea0.png)
