### DISCUSSION TITLE
css selector slides containing specific headers

### DISCUSSION THREAD

**Discussion by infinitesteps** [marp-team/marp#303] [Q&A] [answered]
My H1 slides are my title slides. My H2 slides are my section slides. My H3 slides are my regular slides. I would like to be able to select in my theme CSS a section containing an H1 (or H2, or H3). Is this possible?

For example:

```css
section:has(> h1) {
	background-image: url(title_background.png);
	background-size: cover;
}
```

**Comment by yhatt** [comment, marked as answer]
Yes, that's perfect! However, it's depending on the browser whether to work.

Refer to [the browser compatibility of `:has()` selector at caniuse.com](https://caniuse.com/css-has). At this time, The latest Safari is an only browser supports `:has()`.

**Reply by infinitesteps** [reply]
I am using the vscode extension and generating PDFs. So I am not sure how the browser comes into play. Is there another way besides using has()?

**Reply by yhatt** [reply]
No.

You have to set custom `class` manually via directive instead. This way does not meet your requirement, does it?

```markdown
<!-- _class: bg -->
```

```css
section.bg {
	background-image: url(title_background.png);
	background-size: cover;
}
```
