### DISCUSSION TITLE
Use Noto Emoji font instead of markdown-it-emoji and twemoji

### DISCUSSION THREAD

**Discussion by mil-ad** [marp-team/marp#315] [Q&A] [answered]
Is there a way to disable markdown-it-emoji and twemoji and instead use Google's Noto Color Emoji font?

I can add a new class like below but I want to use Noto everywhere without having to use classes.

```css
.custom_emoji {
  font-family: "Noto Color Emoji"
}
```

I actually thought markdown-it-emoji plugin only deals with converting `:smile:` syntax into emojis but I type mine as direct unicode. So I'm not even sure how they're not picked up by my global font-family config anyway.

**Comment by yhatt** [comment, marked as answer]
Marp Core tries to convert any Unicode emoji characters to Twemoji, including a raw emoji character 😄 and `:smile:` shorthand. Early Chrome had been less reliable in PDF emoji rendering[^1], so we had to adopt aggressive conversion into a unified SVG representation of emoji.

[^1]:  yhatt/marp#57, marp-team/marpit#18, marp-team/marpit#53, marp-team/marp-core#19

We have allowed to disable aggressive emoji conversion to Twemoji by setting the constructor option `emoji`.
https://github.com/marp-team/marp-core#emoji-object

```javascript
const marp = new Marp({
  emoji: {
    shortcode: true, // Turn `:smile:` syntax into Unicode emoji instead of Twemoji
    unicode: false, // Disable agressive converting to Twemoji in Unicode emoji
  }
})
```

If you are using Marp CLI, Marp Core constructor option can set via [the `options` setting in the configuration file](https://github.com/marp-team/marp-cli#configuration-file). (Marp for VS Code cannot fine-tune the core constructor option)

```yaml
# .marprc.yml
options:
  emoji:
    shortcode: true
    unicode: false
```

```
marp -c .marprc.yml your-markdown.md
```

In Markdown, tweak the style for preferring the emoji font than other fonts specified by the theme.[^2]

```css
@import url(https://fonts.googleapis.com/css2?family=Noto+Color+Emoji);

/* for default theme */
section {
  font-family: "Noto Color Emoji",-apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji";
}

/* for gaia theme */
section {
  font-family: "Noto Color Emoji", Lato, 'Avenir Next', Avenir, 'Trebuchet MS', 'Segoe UI', sans-serif;
}

/* for uncover theme */
section {
  font-family: "Noto Color Emoji", -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
}
```

<details><summary>Original definition of font-family is here</summary>

- `default`: https://github.com/sindresorhus/github-markdown-css/blob/9719250aca854ff73070da6c64a579b610773cb3/github-markdown.css#L103 from [`github-markdown-css`](https://github.com/sindresorhus/github-markdown-css) package
- `gaia`: https://github.com/marp-team/marp-core/blob/abc4e2edfae297ba16525270205dcdba161d38f9/themes/gaia.scss#L197-L198
- `uncover`: https://github.com/marp-team/marp-core/blob/abc4e2edfae297ba16525270205dcdba161d38f9/themes/uncover.scss#L31-L32

</details>

And now, you can use Noto Color Emoji in anywhere. :smile:

![](https://user-images.githubusercontent.com/3993388/171405348-efb316f2-75a0-4a93-ad67-543308af1982.png)
