### DISCUSSION TITLE
css style ：pre { white-space: pre-wrap; } cease to be effective！

### DISCUSSION THREAD

**Discussion by yxj1010** [marp-team/marp#321] [Q&A] [answered]
I want the contents of the code block to remain unchanged and wrap automatically, how do I set it?

**Comment by yhatt** [comment, marked as answer]
`<pre>` tags rendered by Marp Core's built-in themes are enabled auto-scaling instead of text wrapping.
https://github.com/marp-team/marp-core/tree/main/themes#auto-scaling-flags

You have to use a custom theme if you want to disable auto-scaling and apply `white-space: pre-wrap` to `<pre>`. Exclude `code` from the scaling targets by using `@auto-scaling` metadata. 

```css
/* @theme custom-theme */
/* @auto-scaling fittingHeader,math */

@import 'default';

pre {
  white-space: pre-wrap;
}
```

### Related

- #159
