### DISCUSSION TITLE
Stretch fonts and margins proportional to the custom theme size preset?

### DISCUSSION THREAD

**Discussion by mtnbjct** [marp-team/marp#334] [Q&A] [answered]
Hi, it's hot here in Japan.

I'm tweaking the gaia theme according to the [marp-core themes README](https://github.com/marp-team/marp-core/tree/main/themes#size-name-width-height) and created this customized theme:

```css
/*!
 * @theme gaia-486
 * @size 1K 1728px 972px
 * @size 2K 1728px 1944px
 * @size 4K 3456px 1944px
 */

@import 'gaia';
```

(These do have the ratio of 16:9 (or the half), and "1K" is 1.35 times of `1280 * 720`, BTW)

Now, it's obvious that fonts and margins get too small when I use the (so-called) "4K" size of gaia-486.
What is the easiest way to stretch the fonts, margins, and whatnot proportional to each preset size so that I can simply tune up the resolution but not changing (so much) from the original `1280 * 720` look? Thank you in advance.

**Comment by yhatt** [comment, marked as answer]
The slide root element `<section>` has `data-size` attribute, it is defined the size preset selected by user. You can apply individual style for each size preset by using [CSS attribute selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors), to set the different root font size.

See also: marp-team/marp-core#134

```css
/*!
 * @theme gaia-486
 * @size 1K 1728px 972px
 * @size 2K 1728px 1944px
 * @size 4K 3456px 1944px
 */

@import 'gaia';

section {
  font-size: 35px; /* The default font size for gaia theme */
}

section[data-size="1K"],
section[data-size="2K"] {
  font-size: 42px; /* x1.2 of the default font size */
}

section[data-size="4K"] {
  font-size: 70px; /* x2 of the default font size */
}
```
