### DISCUSSION TITLE
GitHub actions Marp incubator

### DISCUSSION THREAD

**Discussion by timmens** [marp-team/marp#375] [Q&A] [answered]
Hey!

For my projects, I am calling marp from within Python to help me automate some things. I want to run tests related to this automation on GitHub actions. For this, I need to install the marp-cli during an action run. Is there some preferred way of setting up marp on a runner, maybe something like the [conda incubator](https://github.com/marketplace/actions/setup-miniconda)?

Thank you!

**Comment by yhatt** [comment, marked as answer]
If you used GitHub hosted runner, all dependency to run Marp CLI are already installed (Node.js, Google Chrome). So you just run npx command as below:

```yaml
jobs:
  marp:
    runs-on: ubuntu-latest
    steps:
        - run: npx -y @marp-team/marp-cli@2.2.2 ./slide.md -o ./output.pdf
```

See also: https://github.com/marp-team/marp-cli#npx

If you want to use `marp` command in entire of the workflow for non Node.js project, you can install `marp` globally in early of workflow steps.
https://github.com/marp-team/marp-cli#global-installation
