### DISCUSSION TITLE
CSS: How to change the style of `code`?

### DISCUSSION THREAD

**Discussion by roland-KA** [marp-team/marp#398] [Q&A] [answered]
I've made a CSS-file based on the gaia template (i.e. I did an ```@import 'gaia'```; in my CSS file).

Among other things, I wanted to change the background color and the font color for `code` blocks, using the following specification:

```css
code {
  background-color: ghostwhite !important;
  color: black;
}
```

This works fine for a multiline code block. But when I'm using a code fragment inline, then only the text up to the last character gets the `ghostwhite` background and the rest of the line remains in the color defined by the gaia template.

It looks e.g. like this:
<img width="946" alt="image" src="https://user-images.githubusercontent.com/80126696/209708853-3a773882-4d5e-4766-9357-ec0623ca23d8.png">

How can I get the complete line with the `ghostwite` background?

**Comment by yhatt** [comment, marked as answer]
```css
pre, code {
  background-color: ghostwhite !important;
  color: black;
}
```

Generally [CommonMark transforms the code block in Markdown to the `<code>` element _within the `<pre>` element._](https://spec.commonmark.org/0.30/#example-107) Try styling both `pre` and `code` with the same color style.
