### DISCUSSION TITLE
Right align header

### DISCUSSION THREAD

**Discussion by jtppragg** [marp-team/marp#47] [Q&A] [answered]
I am using a custom css file based on the default style successfully, but I am not able to right align header content. In several slides I have to hide the header for avoiding collision with the title, but it would better for me just moving the header content to the right.

I have tried the following styles without success:
```css
header {
    text-align: right;
    justify-content: right;
}
```
Any idea about how to achieve it?

Thanks!

**Comment by yhatt** [comment, marked as answer]
For default theme:

```css
header {
    left: auto;
    right: 30px;
}
```

or

```css
header {
    right: 30px;
    text-align: right;
}
```
