### DISCUSSION TITLE
how to vertical align only the heading h1 to top.

### DISCUSSION THREAD

**Discussion by cmaspi** [marp-team/marp#478] [Q&A] [answered]
I want to align only the heading to the top but not any other content in the slide.

After hours of googling, I found only the following solution

```
style: |
  section {
    justify-content: start;    
  }
```

However, this aligns everything. Being a novice in CSS, my natural instinct was to use h1 instead of section. That doesn't appear to solve anything though.

**Comment by yhatt** [comment, marked as answer]
A simple solution is using [absolutely positioning](https://developer.mozilla.org/en-US/docs/Web/CSS/position#types_of_positioning) to `h1`.

```yaml
style: |
  h1 {
    position: absolute;
    top: 60px;
    left: 75px;
    right: 75px;
  }
```

Suitable distances for `top`, `left`, and `right` may be different by using theme.

### Another solution

The positioning of absolute element is not affected from other elements, so _may overlap with slide contents if there are a lot of contents._

For centering in cross axis (vertically in this case) with keeping flex items, sandwich main contents with 2 flex items that has `flex-grow: 1`. Following style is using `h1` and a generated empty content to sandwich.

```css
section > h1 {
  flex: 1 0 auto;
  padding: 0;
  margin: 0;
  order: -999999;
}

section:has(> h1)::before {
  flex: 1 0 auto;
  display: block;
  content: '';
  order: 999999;
}
```
