### DISCUSSION TITLE
Open and close quotes (aka real quotes, smart quotes)

### DISCUSSION THREAD

**Discussion by gar1t** [marp-team/marp#481] [Q&A] [answered]
Is there a way to apply real open and close quotes without explicitly using those characters? E.g. `"hello"` to be rendered as “hello”?

**Comment by yhatt** [comment, marked as answer]
Marp CLI can enable [markdown-it](https://github.com/markdown-it/markdown-it)'s `typographer` option through a [config file](https://github.com/marp-team/marp-cli#configuration-file).

```yaml
# .marprc.json
{
  "options": {
    "markdown": {
      "typographer": true
    }
  }
}
```

Marp for VS Code is following VS Code's Markdown setting [`markdown.preview.typographer`](https://code.visualstudio.com/updates/v1_56#_markdown-preview-typographer-support).
