### DISCUSSION TITLE
How to include custom fonts?

### DISCUSSION THREAD

**Discussion by freenandes** [marp-team/marp#484] [Q&A] [answered]
I'm been bumping my head and i'm not sure how to do it. [I've included everything](https://github.com/freenandes/prez/edit/gh-pages/themes/pmcf.css), the assets are there, they are remotely accessible. Why won't the style apply to the element?

![CleanShot 2023-11-16 at 14 02 24@2x](https://github.com/marp-team/marp/assets/42041153/68dbfa5e-c327-4f36-8962-4f83a7215a72)

**Comment by freenandes** [comment, marked as answer]
oh, yeah... I got it. My workflow in Github was not including the necessary theme. So my VSCode has the custom theme (with the fonts references in it) in the VSC prefs.

But to have the theme working ALSO in github the build must include it so we have to call it via CLI. I basically included the location of the folder `themes/pmcf.css`. And then this file is referecing the fonts and applying th style. So on build time `--theme-set build/themes/pmcf.css` must be called. Have in mind this is in the context of using [marp-to-pages](https://github.com/ralexander-phi/marp-to-pages/). I had to replicate it for each file i had to create a file (i don't know how to optimize it).

```yml
- name: Marp Build (README)
    uses: docker://marpteam/marp-cli
    with:
        args: README.md --theme-set build/themes/pmcf.css -o build/index.html
    env:
        MARP_USER: root:root
```
