### DISCUSSION TITLE
Display content on the space assigned to a lateral background image

### DISCUSSION THREAD

**Discussion by jtppragg** [marp-team/marp#49] [Q&A] [answered]
I am using a right-aligned header in order to gain more vertical space for the slide title (on the left) using this solution https://github.com/marp-team/marp/discussions/47#discussioncomment-139350.

However, when including a background image at the right side of the slide (see below), the header is right aligned to the center of the slide instead.

```
![bg right fit](figs/schema.png)
```
Is it possible to keep the header at the right of the slide in this case too?

**Comment by yhatt** [comment, marked as answer]
Any contents including header and footer cannot make a influence into the area for split backgrounds, because `![bg right]()` is for making a reserved space for the background.

<img width="969"  src="https://user-images.githubusercontent.com/3993388/101053348-0563ec80-35cb-11eb-825c-bd09aee7ba12.png">

### Using `section::before`

A only way to place a custom text over the splitted background is using `section::before` pseudo-selector and `content` declaration. 

```css
![bg right](https://picsum.photos/720?image=29)

<style>
section::before {
  content: 'Text over the splitted background!';

  position: absolute;
  right: 30px;
  top: 30px;
  font-size: 60px;
}
</style>
```

<img width="648" src="https://user-images.githubusercontent.com/3993388/101054394-32fd6580-35cc-11eb-9867-d15f620b4764.png">

`section::before` and `section::after` pseudo-elements are designed for the content over the slide and `section::after` is reserved for the pagination by `paginate` directive. Thus, you can use `section::before` only for now.
