### DISCUSSION TITLE
allow multiple theme on a page

### DISCUSSION THREAD

**Discussion by orkeilius** [marp-team/marp#508] [Ideas] [answered]
# allow multiple theme on a page

## why

I could be useful to make theme that add custom layout, animation, feature... while using a "classic" theme 

Example of a class to make a centered layout
```css
section.center > * {
  margin-left:auto;
  margin-right: auto;
  text-align:center;
}
section.center > footer {
  margin: 0;
  text-align:left !important;
}
```
## how 
allow multiple element in theme
`theme : default, my-layout`

## currently
I use a basic style tag in my slide. Maybe an @import could work
