### DISCUSSION TITLE
Is there a way to set the content of the footer in a custom theme?

### DISCUSSION THREAD

**Discussion by alexboly** [marp-team/marp#573] [Q&A] [answered]
Hi,

I wrote my custom theme and I'd like the footer to contain the copyright text. We can copy it in the slides, but I'd prefer if possible to set it from the theme.

I tried setting the content of the footer tag from CSS and setting in :root the --footer variable, without success.

Any suggestions?

Thank you,
Alex

**Comment by yhatt** [comment, marked as answer]
A common way is using [`content` property](https://developer.mozilla.org/docs/Web/CSS/content) within `footer::before` pseudo selector to prepend the specific content by CSS.

```css
/* @theme your-theme */

footer::before {
  content: 'Copyright © 2025 Your Name';
}
```

```markdown
---
theme: your-theme

# Footer directive should be defined as non-empty value to render <footer> tag for each slide page.
footer: " "
---

# Hello!
```

## Alternative

As shown here, `footer` directive should be enabled as non-empty value, such as whitespace(s), to render the `<footer>` element for each slide page. If you want to let theme users show the content specified by theme CSS without using the `footer` directive, you can use `section::before` instead.


```css
/* @theme your-theme */

section::before {
  content: 'Copyright © 2023 Your Name';

  /* Custom styles as the footer */
  position: absolute;
  left: 1rem;
  bottom: 1rem;
  display: block;
  font-size: 1rem;
  color: #999;
}
```
