### DISCUSSION TITLE
Is it possible to define scoped styles in external css?

### DISCUSSION THREAD

**Discussion by mpas** [marp-team/marp#579] [Q&A] [answered]
I was wondering if it was possible to define a style in external css and use it scoped, so that i can use `<!-- _class: style -->` in the page? It would be ideal to reuse scoped styles on multiple pages.

I am using the uncover theme with `invert` but when I try to apply a style to a page the whole section gets reverted.

```css
section.header-left h1 {
  text-align: left;
}
```

```
<!-- _class: header-left -->
# header normally centered
```

I tried to apply this style but the whole page gets the default non inverted colors.

**Comment by yhatt** [comment, marked as answer]
Yes. You can define styles for `class` directive in your custom theme CSS.

```css
/* @theme custom-theme */

@import 'uncover';

section.header-left h1 {
  text-align: left;
}
```

```markdown
---
theme: custom-theme
class: invert
---

# Page 1

---

<!-- _class: invert header-left -->

# Page 2

A scoped `.header-left` class has been applied.

---

# Page 3
```

The `class` directive can define multiple space-separated classes, just like the HTML `class` attribute allows. So you should define the `_class` scoped directive as `invert header-left` to prevent losing the color scheme.
