### ISSUE TITLE
Custom CSS classes are ignored

### ISSUE THREAD

**Issue by wleoncio** [marp-team/marp#45]
# Summary

Marp CLI doesn't seem to recognize some custom CSS elements which Marp VSCode does

# MRE

## `test.md`

```markdown
---
marp: true
theme: test
---
This presentation is <b class=superbold>BLINDING</b>!!!
```

## `test.css`

```css
/* @theme test */
@import 'default';

section {
	color: rebeccapurple;
	background: olivedrab;
}
b.superbold {
	font-weight: bolder;
	font-size: 2em;
}
```

## Terminal command

```bash
marp test.md --theme test.css
```

# Observed output

![image](https://user-images.githubusercontent.com/8234768/100210511-5c066200-2f0b-11eb-9173-701a6ab653f6.png)

So the `section` customizations are properly parsed, but the superbold b class isn't.

# Expected output

![image](https://user-images.githubusercontent.com/8234768/100210347-2feae100-2f0b-11eb-9005-6a007cf3a44f.png)

# Additional comments

The latter is the output from the `Marp: export slide deck...` command on VSC. I tried to discover what command VSC uses so I could try to use it on the CLI as well, but I don't know where to find this.

I tried exporting to PDF, but the output is the same. I've also tried playing around with repositioning the CSS files (between its original `themes/` location and the working directory of the md file), using the `--theme-set` switch, but nothing changed.

I may be doing something improperly here, my CSS skills are quite rudimentary.
